### ISSUE TITLE
Use requests

### ISSUE THREAD

**Issue by palash25** [rajprakash00/pythonscripts#1]
Hi :wave: I saw that you are using urllib to make requests. That library is now obsolete and http://docs.python-requests.org/en/master/ has become the defacto http library for python try using this instead its much simpler and has a better design

P.S. I hope that you are using and writing python 3 instead of 2.7 (if not then better change to python 3 because as of now python 2.7 is unmaintained and no one writes it anymore) :wink:

**Comment by rajprakash00** [comment]
Thanks! For making me aware of this!!:smile:                                                                                                       Um!! I'm actually using python 2.7 but will surely switch to python 3 soon .
